# Generated by Django 4.2.11 on 2024-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("post", models.TextField()),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("entry_date", models.DateTimeField()),
            ],
        ),
    ]
